# Generated by Django 3.0.3 on 2020-02-12 15:03

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qr_kit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='values',
            field=picklefield.fields.PickledObjectField(blank=True, default='', editable=False),
        ),
    ]
