# Generated by Django 3.0.3 on 2020-02-17 14:18

from django.db import migrations, models
import django.db.models.deletion
import qr_kit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qr_kit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCodeReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', qr_kit.models.fields.JSONField(default=dict)),
                ('qr_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='qr_kit.QrCode')),
            ],
        ),
    ]
