# Generated by Django 3.0.3 on 2020-04-05 11:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('qr_kit', '0002_category_redirect_to_form_with_query_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True),
        ),
    ]
