# Generated by Django 3.0.3 on 2020-02-12 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('qr_kit', '0002_auto_20200212_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='values',
            field=models.CharField(max_length=500),
        ),
    ]
