# Generated by Django 3.0.3 on 2020-02-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_kit', '0003_auto_20200212_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='values',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
