# Generated by Django 3.0.3 on 2020-04-16 10:06

from django.db import migrations, models
import django.db.models.deletion
import qr_kit.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('qr_kit', '0003_auto_20200405_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='qr_kit.Category'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='values',
            field=qr_kit.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
    ]
