# Generated by Django 3.0.3 on 2020-02-12 15:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_kit', '0004_auto_20200212_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='values',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
