# Generated by Django 2.2.4 on 2019-10-14 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobqr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackeditem',
            name='is_in_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackeditem',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobqr.Job'),
        ),
    ]
