# Generated by Django 2.2.4 on 2019-11-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackeditem',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
