# Generated by Django 2.2.4 on 2019-11-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqr', '0002_trackeditem_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackeditem',
            name='missing',
            field=models.BooleanField(default=False),
        ),
    ]
