# Generated by Django 2.2.4 on 2019-11-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqr', '0004_method_methodtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodtemplate',
            name='methods',
            field=models.ManyToManyField(related_name='template', related_query_name='template', to='jobqr.Method'),
        ),
    ]
