# Generated by Django 3.0.3 on 2020-04-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads_qr_kit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobimage',
            name='stored_image',
            field=models.ImageField(upload_to='img/jobs/'),
        ),
        migrations.DeleteModel(
            name='StoredImage',
        ),
    ]
