# Generated by Django 3.0.3 on 2020-03-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads_qr_kit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackeditem',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
