# Generated by Django 3.0.3 on 2020-03-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roads_qr_kit', '0002_auto_20200305_1421'),
        ('roads_qr_kit', '0002_auto_20200305_1412'),
    ]

    operations = [
    ]
