# Generated by Django 3.0.3 on 2020-04-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads_qr_kit', '0003_jobimage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobimage',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
