# Generated by Django 3.0.3 on 2020-06-30 10:42

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('roads_qr_kit', '0006_job_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='', editable=False, max_length=63),
            preserve_default=False,
        ),
    ]
