# Generated by Django 3.1.1 on 2020-09-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads_qr_kit', '0008_auto_20200630_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='', max_length=128),
        ),
    ]
