# Generated by Django 2.2.4 on 2019-08-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotqrcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='city',
            field=models.CharField(default='Ghent', max_length=255),
        ),
    ]
