# Generated by Django 2.2.4 on 2019-09-25 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iotqrcode', '0003_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='end',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
